/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  PackageVersioned,
  PackageVersionedInterface,
} from "../PackageVersioned";

const _abi = [
  {
    inputs: [],
    name: "PACKAGE_VERSION",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class PackageVersioned__factory {
  static readonly abi = _abi;
  static createInterface(): PackageVersionedInterface {
    return new utils.Interface(_abi) as PackageVersionedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PackageVersioned {
    return new Contract(address, _abi, signerOrProvider) as PackageVersioned;
  }
}
