/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "MailboxClient",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MailboxClient__factory>;
    getContractFactory(
      name: "Router",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Router__factory>;
    getContractFactory(
      name: "StandardHookMetadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StandardHookMetadata__factory>;
    getContractFactory(
      name: "IPostDispatchHook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPostDispatchHook__factory>;
    getContractFactory(
      name: "IInterchainSecurityModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IInterchainSecurityModule__factory>;
    getContractFactory(
      name: "ISpecifiesInterchainSecurityModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISpecifiesInterchainSecurityModule__factory>;
    getContractFactory(
      name: "IMailbox",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMailbox__factory>;
    getContractFactory(
      name: "IMessageRecipient",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMessageRecipient__factory>;
    getContractFactory(
      name: "PackageVersioned",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PackageVersioned__factory>;
    getContractFactory(
      name: "OwnableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwnableUpgradeable__factory>;
    getContractFactory(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Initializable__factory>;
    getContractFactory(
      name: "ContextUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ContextUpgradeable__factory>;
    getContractFactory(
      name: "LogoHuntGame",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LogoHuntGame__factory>;
    getContractFactory(
      name: "MockClient",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockClient__factory>;

    getContractAt(
      name: "MailboxClient",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MailboxClient>;
    getContractAt(
      name: "Router",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Router>;
    getContractAt(
      name: "StandardHookMetadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.StandardHookMetadata>;
    getContractAt(
      name: "IPostDispatchHook",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IPostDispatchHook>;
    getContractAt(
      name: "IInterchainSecurityModule",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IInterchainSecurityModule>;
    getContractAt(
      name: "ISpecifiesInterchainSecurityModule",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ISpecifiesInterchainSecurityModule>;
    getContractAt(
      name: "IMailbox",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMailbox>;
    getContractAt(
      name: "IMessageRecipient",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMessageRecipient>;
    getContractAt(
      name: "PackageVersioned",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PackageVersioned>;
    getContractAt(
      name: "OwnableUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwnableUpgradeable>;
    getContractAt(
      name: "Initializable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Initializable>;
    getContractAt(
      name: "ContextUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ContextUpgradeable>;
    getContractAt(
      name: "LogoHuntGame",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LogoHuntGame>;
    getContractAt(
      name: "MockClient",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockClient>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
