/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface StandardHookMetadataInterface extends utils.Interface {
  functions: {
    "VARIANT()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "VARIANT", values?: undefined): string;

  decodeFunctionResult(functionFragment: "VARIANT", data: BytesLike): Result;

  events: {};
}

export interface StandardHookMetadata extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: StandardHookMetadataInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    VARIANT(overrides?: CallOverrides): Promise<[number]>;
  };

  VARIANT(overrides?: CallOverrides): Promise<number>;

  callStatic: {
    VARIANT(overrides?: CallOverrides): Promise<number>;
  };

  filters: {};

  estimateGas: {
    VARIANT(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    VARIANT(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
